name: brave_search
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  # state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  injectable: ^2.5.1


  # network
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  
  # ui utilities
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.2.0
  
  # connectivity
  internet_connection_checker_plus: ^2.7.2
  connectivity_plus: ^6.1.5
  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  webview_flutter: ^4.10.0
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linting
  flutter_lints: ^4.0.0

  # code generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1



flutter:


  uses-material-design: true

 
  assets:
    - .env
    - assets/images/brave_color_darkbackground.png
    - assets/images/brave_color_lightbackground.png
    - assets/animations/Web Search..json
    - assets/animations/SearchingW.json
